"""Initial migration

Revision ID: 215419d37f80
Revises: 
Create Date: 2024-07-18 19:30:39.819665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215419d37f80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=True),
    sa.Column('practice_name', sa.String(length=128), nullable=True),
    sa.Column('doctor_name', sa.String(length=128), nullable=True),
    sa.Column('patient_name', sa.String(length=128), nullable=True),
    sa.Column('lab_slip_number', sa.String(length=64), nullable=True),
    sa.Column('job_status', sa.String(length=64), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('shade', sa.String(length=64), nullable=True),
    sa.Column('invoice_number', sa.String(length=64), nullable=True),
    sa.Column('delivery_info', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_slip_number')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('job')
    # ### end Alembic commands ###
