"""Add comments to Job model

Revision ID: c23dc23c9b32
Revises: c28898f14a6b
Create Date: 2024-07-19 19:51:00.671958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23dc23c9b32'
down_revision = 'c28898f14a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'comments')
    # ### end Alembic commands ###
